accelerate launch train_controlnet.py \
--pretrained_model_name_or_path="stabilityai/stable-diffusion-2-1-base" \
--output_dir="/mnt/shared/RoomNet-supermlsd" \
--dataset_name="endyai/RoomNet" \
--conditioning_image_column=full_superimposed \
--image_column=empty \
--caption_column=empty_caption \
--resolution=512 \
--learning_rate=1e-5 \
--validation_image "./validation_images/living_room_superimposed_1.jpeg" "./validation_images/living_room_superimposed_2.jpeg" "././validation_images/living_room_superimposed_3.jpeg" \
--validation_prompt "an empty room with white walls and windows" "an empty room with white walls, big window and hardwood floors" "an empty room with dark gray walls, and hardwood floors" \
--train_batch_size=4 \
--num_train_epochs=50 \
--tracker_project_name="RoomNet-supermlsd" \
--enable_xformers_memory_efficient_attention \
--checkpointing_steps=5000 \
--validation_steps=5000 \
--report_to wandb \
--resume_from_checkpoint=latest \
--push_to_hub